# Generated by Django 3.0.7 on 2020-06-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200608_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='asset_id',
            new_name='coin_id',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='price_usd',
            new_name='price',
        ),
        migrations.AddField(
            model_name='coin',
            name='icon',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='symbol',
            field=models.CharField(default=' ', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
